variable "secrets_dir" {}

# This module will install Tiller into your namespace and use
# TLS assets generated by helm-tls module.
# By default, module is looking into the following directory for TLS assets:
# ${TF_VAR_secrets_dir}/${custom_tls_dir:-tiller-namespace}/${helm_dir_name}


variable "custom_tls_dir" {
  default = ""
}

variable "helm_dir_name" {
  default = "helm-tls"
}

variable "tiller_namespace" {
  default = "kube-system"
}

variable "tiller_connection_timeout" {
  default     = "30"
  description = "How long will Helm wait to establish a connection to tiller"
}
